spring:

  jpa:
    hibernate:
      ddl-auto: none   # managed by liquibase
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:campustrade_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: test
    password: test

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/master.yaml

server:
  port: 8080
  servlet:
    context-path: /campustrade
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

  level:
    root: INFO
    com.marvin.campustrade: DEBUG

    # SQL queries
    org.hibernate.SQL: DEBUG

    # SQL bind parameters
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

    # transaction events
    org.springframework.orm.jpa.JpaTransactionManager: DEBUG